-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'PACKAGE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'PACKAGE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'PACKAGE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'PACKAGE_EXPENSE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'PACKAGE_EXPENSE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'PACKAGE_EXPENSE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'PACKAGE_BASELINE_SAVED';
ALTER TYPE "AuditAction" ADD VALUE 'SURVEY_ASSIGNMENT_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'SURVEY_ASSIGNMENT_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'SURVEY_RESPONSE_SUBMITTED';
ALTER TYPE "AuditAction" ADD VALUE 'SURVEY_RESPONSE_ACCEPTED';
ALTER TYPE "AuditAction" ADD VALUE 'SURVEY_RESPONSE_REJECTED';
ALTER TYPE "AuditAction" ADD VALUE 'SURVEY_RESPONSE_REVERTED';

-- CreateIndex
CREATE INDEX "audit_logs_resource_type_resource_id_created_at_idx" ON "audit_logs"("resource_type", "resource_id", "created_at");
