export enum AuditAction {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_CREDENTIALS_RESET = 'USER_CREDENTIALS_RESET',
  PACKAGE_CREATED = 'PACKAGE_CREATED',
  PACKAGE_UPDATED = 'PACKAGE_UPDATED',
  PACKAGE_DELETED = 'PACKAGE_DELETED',
  PACKAGE_EXPENSE_CREATED = 'PACKAGE_EXPENSE_CREATED',
  PACKAGE_EXPENSE_UPDATED = 'PACKAGE_EXPENSE_UPDATED',
  PACKAGE_EXPENSE_DELETED = 'PACKAGE_EXPENSE_DELETED',
  PACKAGE_BASELINE_SAVED = 'PACKAGE_BASELINE_SAVED',
  SURVEY_ASSIGNMENT_CREATED = 'SURVEY_ASSIGNMENT_CREATED',
  SURVEY_ASSIGNMENT_DELETED = 'SURVEY_ASSIGNMENT_DELETED',
  SURVEY_ASSIGNMENT_UPDATED = 'SURVEY_ASSIGNMENT_UPDATED',
  SURVEY_RESPONSE_SUBMITTED = 'SURVEY_RESPONSE_SUBMITTED',
  SURVEY_RESPONSE_ACCEPTED = 'SURVEY_RESPONSE_ACCEPTED',
  SURVEY_RESPONSE_REJECTED = 'SURVEY_RESPONSE_REJECTED',
  SURVEY_RESPONSE_REVERTED = 'SURVEY_RESPONSE_REVERTED',
  MOBILE_APP_UPLOADED = 'MOBILE_APP_UPLOADED',
}

export const AUDIT_RESOURCE_TYPES = {
  USER: 'user',
  PROCUREMENT_PACKAGE: 'procurement_package',
  MOBILE_APP_RELEASE: 'mobile_app_release',
} as const;

export class AuditLog {
  constructor(
    public readonly id: string,
    public readonly actorId: string,
    public readonly action: AuditAction,
    public readonly resourceType: string,
    public readonly resourceId: string | null,
    public readonly metadata: Record<string, unknown> | null,
    public readonly createdAt: Date,
    public readonly actorEmail?: string,
    public readonly actorUsername?: string,
  ) {}
}
